using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DancingManagementSystem
{
    public partial class View_Admin_Registered : Form
    {
        //variables
        private MySQLConnection sqlConn;
        private DataTable dtTableClass;
        private DataTable dtTableMember;

        //
        // Constructor
        //
        public View_Admin_Registered(MySQLConnection sqlConn)
        {
            //Initialize visual windows form
            InitializeComponent();

            //Assign parameters to local variables
            this.sqlConn = sqlConn;

        }

        //
        // This method query the database for the list of member of particular class and return DataTable
        //
        private void getMemberList(string classIndex)
        {
            //Initiate a new connection
            sqlConn = new MySQLConnection();

            //SQL command
            string sqlCommand = "SELECT d.user_id, concat(d.user_first_name, ' ', d.user_last_name) AS user_name "
                                + "FROM registered_class rc, user_data d "
                                + "WHERE rc.user_data_user_id = d.user_id "
                                + "AND rc.dance_class_class_id =" + classIndex + ";";

            //Execute and assign DataTable object
            dtTableMember = sqlConn.select_Using_DataAdapter(sqlCommand);

            //Populate the new member list to the ListView
            listMember.DataSource = dtTableMember;
            listMember.DisplayMember = "user_name";
            listMember.ValueMember = "user_id";
        } //end of getMemberList()

        //
        // This method is called when the form is loaded. It queries the database and get the list of available classes
        //
        private void View_Admin_Registered_Load(object sender, EventArgs e)
        {
            //Set the default combobox selected item to a blank one
            comboClass.SelectedIndex = -1;

            //Initiate a new connection
            sqlConn = new MySQLConnection();

            //SQL command
            string sqlCommand = "SELECT class_title, class_id FROM dance_class ORDER BY class_title ASC;";

            //Execute and assign DataTable object
            dtTableClass = sqlConn.select_Using_DataAdapter(sqlCommand);

            //Populate the list of class to the combobox
            comboClass.DataSource = dtTableClass;
            comboClass.DisplayMember = "class_title";
            comboClass.ValueMember = "class_id";
        }// end of View_Admin_Registered_Load()


        //
        // This method is to handle the event generated by clicking button Show Members
        //
        private void btnShow_Click(object sender, EventArgs e)
        {
            //Get the list of the member of the selected class
            getMemberList(comboClass.SelectedValue.ToString());
        }

        //
        // This method is to handle the event generated by clicking button Member Details
        //
        private void btnDetail_Click(object sender, EventArgs e)
        {
            sqlConn = new MySQLConnection();

            string sqlCommand = "SELECT * FROM user_data WHERE user_id=" + listMember.SelectedValue.ToString() + ";";

            DataTable dt = sqlConn.select_Using_DataAdapter(sqlCommand);

            var user = dt.Rows[0].ItemArray.Select(x => x.ToString()).ToArray();

            var form = new View_User_User(user);
            form.ShowDialog();
        }
    }// end of class
}
